"""
Mongo Aggro - MongoDB Aggregation Pipeline Builder with Pydantic.

A Python package for building MongoDB aggregation pipelines with
strong type checking using Pydantic models.

Example:
    >>> from mongo_aggro import Pipeline, Match, Unwind, Group, Sort, Limit
    >>>
    >>> pipeline = Pipeline()
    >>> pipeline.add_stage(Match(query={"status": "active"}))
    >>> pipeline.add_stage(Unwind(path="items"))
    >>> pipeline.add_stage(Group(id="$category", count={"$sum": 1}))
    >>> pipeline.add_stage(Sort(fields={"count": -1}))
    >>> pipeline.add_stage(Limit(count=10))
    >>>
    >>> # Pass directly to MongoDB - no need to call any methods
    >>> results = collection.aggregate(pipeline)

Expression operators with Python syntax:
    >>> from mongo_aggro import Match, Expr
    >>> from mongo_aggro.expressions import F
    >>>
    >>> # Use Python operators for MongoDB expressions
    >>> Match(query=Expr((F("status") == "active") & (F("age") > 18)))
"""

from .accumulators import (
    Accumulate,
    Accumulator,
    AddToSet,
    Avg,
    BottomN,
    Count_,
    First,
    FirstN,
    Last,
    LastN,
    Max,
    MaxN,
    MergeObjects,
    Min,
    MinN,
    Push,
    StdDevPop,
    StdDevSamp,
    Sum,
    TopN,
    merge_accumulators,
)
from .base import (
    ASCENDING,
    DESCENDING,
    AggregationInput,
    BaseStage,
    Pipeline,
    SortSpec,
    serialize_value,
)
from .expressions import (
    # Arithmetic expressions
    AbsExpr,
    AddExpr,
    # Set expressions
    AllElementsTrueExpr,
    # Comparison expressions
    AndExpr,
    AnyElementTrueExpr,
    # Array expressions
    ArrayElemAtExpr,
    ArraySizeExpr,
    ArrayToObjectExpr,
    CeilExpr,
    CmpExpr,
    ConcatArraysExpr,
    ConcatExpr,
    # Conditional expressions
    CondExpr,
    # Type conversion expressions
    ConvertExpr,
    # Date expressions
    DateAddExpr,
    DateDiffExpr,
    DateFromStringExpr,
    DateSubtractExpr,
    DateToStringExpr,
    DivideExpr,
    EqExpr,
    ExpExpr,
    ExpressionBase,
    F,
    Field,
    FilterExpr,
    FirstNExpr,
    FloorExpr,
    # Object expressions
    GetFieldExpr,
    GteExpr,
    GtExpr,
    IfNullExpr,
    # Additional array expressions
    InArrayExpr,
    IndexOfArrayExpr,
    IsArrayExpr,
    IsNumberExpr,
    LastNExpr,
    # Variable expressions
    LetExpr,
    # Miscellaneous expressions
    LiteralExpr,
    LnExpr,
    Log10Expr,
    LogExpr,
    LteExpr,
    LtExpr,
    LTrimExpr,
    MapExpr,
    MaxNExpr,
    # Object expressions
    MergeObjectsExpr,
    MinNExpr,
    ModExpr,
    MultiplyExpr,
    NeExpr,
    # Logical expressions
    NotExpr,
    ObjectToArrayExpr,
    OrExpr,
    PowExpr,
    RandExpr,
    RangeExpr,
    ReduceExpr,
    # Regex expressions
    RegexFindAllExpr,
    RegexFindExpr,
    RegexMatchExpr,
    ReplaceAllExpr,
    ReplaceOneExpr,
    ReverseArrayExpr,
    RoundExpr,
    RTrimExpr,
    # Set expressions
    SetDifferenceExpr,
    SetEqualsExpr,
    SetFieldExpr,
    SetIntersectionExpr,
    SetIsSubsetExpr,
    SetUnionExpr,
    SliceExpr,
    SortArrayExpr,
    # String expressions
    SplitExpr,
    SqrtExpr,
    StrCaseCmpExpr,
    StrLenCPExpr,
    SubstrCPExpr,
    SubtractExpr,
    SwitchBranch,
    SwitchExpr,
    ToBoolExpr,
    ToDateExpr,
    ToDecimalExpr,
    ToDoubleExpr,
    ToIntExpr,
    ToLongExpr,
    ToLowerExpr,
    ToObjectIdExpr,
    ToStringExpr,
    ToUpperExpr,
    TrimExpr,
    TruncExpr,
    TypeExpr,
)
from .operators import (
    All,
    And,
    ElemMatch,
    Eq,
    Exists,
    Expr,
    Gt,
    Gte,
    In,
    Lt,
    Lte,
    Ne,
    Nin,
    Nor,
    Not,
    Or,
    QueryOperator,
    Regex,
    Size,
    Type,
)
from .stages import (
    AddFields,
    Bucket,
    BucketAuto,
    Count,
    Densify,
    Documents,
    Facet,
    Fill,
    GeoNear,
    GraphLookup,
    Group,
    Limit,
    Lookup,
    Match,
    Merge,
    Out,
    Project,
    Redact,
    ReplaceRoot,
    ReplaceWith,
    Sample,
    Set,
    SetWindowFields,
    Skip,
    Sort,
    SortByCount,
    UnionWith,
    Unset,
    Unwind,
)

__all__ = [
    # Base classes and types
    "Pipeline",
    "BaseStage",
    "SortSpec",
    "AggregationInput",
    "serialize_value",
    # Sort direction constants
    "ASCENDING",
    "DESCENDING",
    # Expression operators (new)
    "F",
    "Field",
    "ExpressionBase",
    "EqExpr",
    "NeExpr",
    "GtExpr",
    "GteExpr",
    "LtExpr",
    "LteExpr",
    "CmpExpr",
    "AndExpr",
    "OrExpr",
    "NotExpr",
    # Arithmetic expressions
    "AddExpr",
    "SubtractExpr",
    "MultiplyExpr",
    "DivideExpr",
    "AbsExpr",
    "ModExpr",
    # Conditional expressions
    "CondExpr",
    "IfNullExpr",
    "SwitchExpr",
    "SwitchBranch",
    # String expressions
    "ConcatExpr",
    "SplitExpr",
    "ToLowerExpr",
    "ToUpperExpr",
    # Array expressions
    "ArraySizeExpr",
    "SliceExpr",
    "FilterExpr",
    "MapExpr",
    "ReduceExpr",
    # Date expressions
    "DateAddExpr",
    "DateSubtractExpr",
    "DateDiffExpr",
    "DateToStringExpr",
    "DateFromStringExpr",
    # Type conversion expressions
    "ToDateExpr",
    "ToStringExpr",
    "ToIntExpr",
    "ToDoubleExpr",
    "ToBoolExpr",
    "ToObjectIdExpr",
    "ConvertExpr",
    "TypeExpr",
    "ToLongExpr",
    "ToDecimalExpr",
    "IsNumberExpr",
    # Set expressions
    "SetUnionExpr",
    "SetIntersectionExpr",
    "SetDifferenceExpr",
    "SetEqualsExpr",
    "SetIsSubsetExpr",
    "AnyElementTrueExpr",
    "AllElementsTrueExpr",
    # Object expressions
    "MergeObjectsExpr",
    "ObjectToArrayExpr",
    "ArrayToObjectExpr",
    "GetFieldExpr",
    "SetFieldExpr",
    # Variable expressions
    "LetExpr",
    # Miscellaneous expressions
    "LiteralExpr",
    "RandExpr",
    # Additional array expressions
    "ArrayElemAtExpr",
    "ConcatArraysExpr",
    "InArrayExpr",
    "IndexOfArrayExpr",
    "IsArrayExpr",
    "ReverseArrayExpr",
    "SortArrayExpr",
    "RangeExpr",
    "FirstNExpr",
    "LastNExpr",
    "MaxNExpr",
    "MinNExpr",
    # Additional string expressions
    "TrimExpr",
    "LTrimExpr",
    "RTrimExpr",
    "ReplaceOneExpr",
    "ReplaceAllExpr",
    "RegexMatchExpr",
    "RegexFindExpr",
    "RegexFindAllExpr",
    "SubstrCPExpr",
    "StrLenCPExpr",
    "StrCaseCmpExpr",
    # Additional arithmetic expressions
    "CeilExpr",
    "FloorExpr",
    "RoundExpr",
    "TruncExpr",
    "SqrtExpr",
    "PowExpr",
    "ExpExpr",
    "LnExpr",
    "Log10Expr",
    "LogExpr",
    # Query operators
    "QueryOperator",
    "And",
    "Or",
    "Not",
    "Nor",
    "Expr",
    "Eq",
    "Ne",
    "Gt",
    "Gte",
    "Lt",
    "Lte",
    "In",
    "Nin",
    "Regex",
    "Exists",
    "Type",
    "ElemMatch",
    "Size",
    "All",
    # Accumulators
    "Accumulator",
    "Sum",
    "Avg",
    "Min",
    "Max",
    "First",
    "Last",
    "Push",
    "AddToSet",
    "StdDevPop",
    "StdDevSamp",
    "Count_",
    "MergeObjects",
    "Accumulate",
    "TopN",
    "BottomN",
    "FirstN",
    "LastN",
    "MaxN",
    "MinN",
    "merge_accumulators",
    # Stages
    "Match",
    "Project",
    "Group",
    "Sort",
    "Limit",
    "Skip",
    "Unwind",
    "Lookup",
    "AddFields",
    "Set",
    "Unset",
    "Count",
    "SortByCount",
    "Facet",
    "Bucket",
    "BucketAuto",
    "ReplaceRoot",
    "ReplaceWith",
    "Sample",
    "Out",
    "Merge",
    "Redact",
    "UnionWith",
    "GeoNear",
    "GraphLookup",
    "SetWindowFields",
    "Densify",
    "Fill",
    "Documents",
]
