"""
Mongo Aggro - MongoDB Aggregation Pipeline Builder with Pydantic.

A Python package for building MongoDB aggregation pipelines with
strong type checking using Pydantic models.

Example:
    >>> from mongo_aggro import Pipeline, Match, Unwind, Group, Sort, Limit
    >>>
    >>> pipeline = Pipeline()
    >>> pipeline.add_stage(Match(query={"status": "active"}))
    >>> pipeline.add_stage(Unwind(path="items"))
    >>> pipeline.add_stage(Group(id="$category", count={"$sum": 1}))
    >>> pipeline.add_stage(Sort(fields={"count": -1}))
    >>> pipeline.add_stage(Limit(count=10))
    >>>
    >>> # Pass directly to MongoDB - no need to call any methods
    >>> results = collection.aggregate(pipeline)

Expression operators with Python syntax:
    >>> from mongo_aggro import Match, Expr
    >>> from mongo_aggro.expressions import F
    >>>
    >>> # Use Python operators for MongoDB expressions
    >>> Match(query=Expr((F("status") == "active") & (F("age") > 18)))
"""

from .accumulators import (
    Accumulate,
    Accumulator,
    AddToSet,
    Avg,
    BottomN,
    Count_,
    First,
    FirstN,
    Last,
    LastN,
    Max,
    MaxN,
    MergeObjects,
    Min,
    MinN,
    Push,
    StdDevPop,
    StdDevSamp,
    Sum,
    TopN,
    merge_accumulators,
)
from .base import (
    ASCENDING,
    DESCENDING,
    AggregationInput,
    BaseStage,
    Pipeline,
    SortSpec,
    serialize_value,
)
from .expressions import (
    # Arithmetic expressions
    AbsExpr,
    AcosExpr,
    AcoshExpr,
    AddExpr,
    # Set expressions
    AllElementsTrueExpr,
    # Comparison expressions
    AndExpr,
    AnyElementTrueExpr,
    # Array expressions
    ArrayElemAtExpr,
    ArraySizeExpr,
    ArrayToObjectExpr,
    AsinExpr,
    AsinhExpr,
    Atan2Expr,
    AtanExpr,
    AtanhExpr,
    BinarySizeExpr,
    BitAndExpr,
    BitNotExpr,
    BitOrExpr,
    BitXorExpr,
    BottomExpr,
    BottomNWindowExpr,
    BsonSizeExpr,
    CeilExpr,
    CmpExpr,
    ConcatArraysExpr,
    ConcatExpr,
    # Conditional expressions
    CondExpr,
    # Type conversion expressions
    ConvertExpr,
    CosExpr,
    CoshExpr,
    CovariancePopExpr,
    CovarianceSampExpr,
    # Date expressions
    DateAddExpr,
    DateDiffExpr,
    DateFromPartsExpr,
    DateFromStringExpr,
    DateSubtractExpr,
    DateToPartsExpr,
    DateToStringExpr,
    DateTruncExpr,
    DayOfMonthExpr,
    DayOfWeekExpr,
    DayOfYearExpr,
    DegreesToRadiansExpr,
    DenseRankExpr,
    DerivativeExpr,
    DivideExpr,
    DocumentNumberExpr,
    # Encrypted string expressions
    EncStrContainsExpr,
    EncStrEndsWithExpr,
    EncStrNormalizedEqExpr,
    EncStrStartsWithExpr,
    EqExpr,
    ExpExpr,
    ExpMovingAvgExpr,
    ExpressionBase,
    F,
    Field,
    FilterExpr,
    FirstNExpr,
    FloorExpr,
    # Object expressions
    GetFieldExpr,
    GteExpr,
    GtExpr,
    HourExpr,
    IfNullExpr,
    # Additional array expressions
    InArrayExpr,
    IndexOfArrayExpr,
    IntegralExpr,
    IsArrayExpr,
    IsNumberExpr,
    IsoDayOfWeekExpr,
    IsoWeekExpr,
    IsoWeekYearExpr,
    LastNExpr,
    # Variable expressions
    LetExpr,
    LinearFillExpr,
    # Miscellaneous expressions
    LiteralExpr,
    LnExpr,
    LocfExpr,
    Log10Expr,
    LogExpr,
    LteExpr,
    LtExpr,
    LTrimExpr,
    MapExpr,
    MaxNExpr,
    # Object expressions
    MergeObjectsExpr,
    MillisecondExpr,
    MinNExpr,
    MinuteExpr,
    ModExpr,
    MonthExpr,
    MultiplyExpr,
    NeExpr,
    # Logical expressions
    NotExpr,
    ObjectToArrayExpr,
    OrExpr,
    PowExpr,
    RadiansToDegreesExpr,
    RandExpr,
    RangeExpr,
    # Window expressions
    RankExpr,
    ReduceExpr,
    # Regex expressions
    RegexFindAllExpr,
    RegexFindExpr,
    RegexMatchExpr,
    ReplaceAllExpr,
    ReplaceOneExpr,
    ReverseArrayExpr,
    RoundExpr,
    RTrimExpr,
    SecondExpr,
    # Set expressions
    SetDifferenceExpr,
    SetEqualsExpr,
    SetFieldExpr,
    SetIntersectionExpr,
    SetIsSubsetExpr,
    SetUnionExpr,
    ShiftExpr,
    SinExpr,
    SinhExpr,
    SliceExpr,
    SortArrayExpr,
    # String expressions
    SplitExpr,
    SqrtExpr,
    StrCaseCmpExpr,
    StrLenCPExpr,
    SubstrCPExpr,
    SubtractExpr,
    SwitchBranch,
    SwitchExpr,
    TanExpr,
    TanhExpr,
    ToBoolExpr,
    ToDateExpr,
    ToDecimalExpr,
    ToDoubleExpr,
    ToIntExpr,
    ToLongExpr,
    ToLowerExpr,
    ToObjectIdExpr,
    TopExpr,
    TopNWindowExpr,
    ToStringExpr,
    ToUpperExpr,
    TrimExpr,
    TruncExpr,
    TypeExpr,
    WeekExpr,
    YearExpr,
)
from .operators import (
    All,
    And,
    BitsAllClear,
    BitsAllSet,
    BitsAnyClear,
    BitsAnySet,
    ElemMatch,
    Eq,
    Exists,
    Expr,
    GeoIntersects,
    GeoWithin,
    Gt,
    Gte,
    In,
    JsonSchema,
    Lt,
    Lte,
    Mod,
    Ne,
    Near,
    NearSphere,
    Nin,
    Nor,
    Not,
    Or,
    QueryOperator,
    Regex,
    Size,
    Text,
    Type,
    Where,
)
from .stages import (
    AddFields,
    Bucket,
    BucketAuto,
    ChangeStream,
    ChangeStreamSplitLargeEvent,
    CollStats,
    Count,
    CurrentOp,
    Densify,
    Documents,
    Facet,
    Fill,
    GeoNear,
    GraphLookup,
    Group,
    IndexStats,
    Limit,
    ListClusterCatalog,
    ListLocalSessions,
    ListSampledQueries,
    ListSearchIndexes,
    ListSessions,
    Lookup,
    Match,
    Merge,
    Out,
    PlanCacheStats,
    Project,
    QuerySettings,
    RankFusion,
    Redact,
    ReplaceRoot,
    ReplaceWith,
    Sample,
    Search,
    SearchMeta,
    Set,
    SetWindowFields,
    Skip,
    Sort,
    SortByCount,
    UnionWith,
    Unset,
    Unwind,
    VectorSearch,
)

__all__ = [
    # Base classes and types
    "Pipeline",
    "BaseStage",
    "SortSpec",
    "AggregationInput",
    "serialize_value",
    # Sort direction constants
    "ASCENDING",
    "DESCENDING",
    # Expression operators (new)
    "F",
    "Field",
    "ExpressionBase",
    "EqExpr",
    "NeExpr",
    "GtExpr",
    "GteExpr",
    "LtExpr",
    "LteExpr",
    "CmpExpr",
    "AndExpr",
    "OrExpr",
    "NotExpr",
    # Arithmetic expressions
    "AddExpr",
    "SubtractExpr",
    "MultiplyExpr",
    "DivideExpr",
    "AbsExpr",
    "ModExpr",
    # Conditional expressions
    "CondExpr",
    "IfNullExpr",
    "SwitchExpr",
    "SwitchBranch",
    # String expressions
    "ConcatExpr",
    "SplitExpr",
    "ToLowerExpr",
    "ToUpperExpr",
    # Array expressions
    "ArraySizeExpr",
    "SliceExpr",
    "FilterExpr",
    "MapExpr",
    "ReduceExpr",
    # Date expressions
    "DateAddExpr",
    "DateSubtractExpr",
    "DateDiffExpr",
    "DateToStringExpr",
    "DateFromStringExpr",
    # Type conversion expressions
    "ToDateExpr",
    "ToStringExpr",
    "ToIntExpr",
    "ToDoubleExpr",
    "ToBoolExpr",
    "ToObjectIdExpr",
    "ConvertExpr",
    "TypeExpr",
    "ToLongExpr",
    "ToDecimalExpr",
    "IsNumberExpr",
    # Set expressions
    "SetUnionExpr",
    "SetIntersectionExpr",
    "SetDifferenceExpr",
    "SetEqualsExpr",
    "SetIsSubsetExpr",
    "AnyElementTrueExpr",
    "AllElementsTrueExpr",
    # Object expressions
    "MergeObjectsExpr",
    "ObjectToArrayExpr",
    "ArrayToObjectExpr",
    "GetFieldExpr",
    "SetFieldExpr",
    # Variable expressions
    "LetExpr",
    # Miscellaneous expressions
    "LiteralExpr",
    "RandExpr",
    # Additional array expressions
    "ArrayElemAtExpr",
    "ConcatArraysExpr",
    "InArrayExpr",
    "IndexOfArrayExpr",
    "IsArrayExpr",
    "ReverseArrayExpr",
    "SortArrayExpr",
    "RangeExpr",
    "FirstNExpr",
    "LastNExpr",
    "MaxNExpr",
    "MinNExpr",
    # Additional string expressions
    "TrimExpr",
    "LTrimExpr",
    "RTrimExpr",
    "ReplaceOneExpr",
    "ReplaceAllExpr",
    "RegexMatchExpr",
    "RegexFindExpr",
    "RegexFindAllExpr",
    "SubstrCPExpr",
    "StrLenCPExpr",
    "StrCaseCmpExpr",
    # Additional arithmetic expressions
    "CeilExpr",
    "FloorExpr",
    "RoundExpr",
    "TruncExpr",
    "SqrtExpr",
    "PowExpr",
    "ExpExpr",
    "LnExpr",
    "Log10Expr",
    "LogExpr",
    # Trigonometry expressions
    "SinExpr",
    "CosExpr",
    "TanExpr",
    "AsinExpr",
    "AcosExpr",
    "AtanExpr",
    "Atan2Expr",
    "SinhExpr",
    "CoshExpr",
    "TanhExpr",
    "AsinhExpr",
    "AcoshExpr",
    "AtanhExpr",
    "DegreesToRadiansExpr",
    "RadiansToDegreesExpr",
    # Bitwise expressions
    "BitAndExpr",
    "BitOrExpr",
    "BitXorExpr",
    "BitNotExpr",
    # Data size expressions
    "BsonSizeExpr",
    "BinarySizeExpr",
    # Date part expressions
    "YearExpr",
    "MonthExpr",
    "DayOfMonthExpr",
    "DayOfWeekExpr",
    "DayOfYearExpr",
    "HourExpr",
    "MinuteExpr",
    "SecondExpr",
    "MillisecondExpr",
    "WeekExpr",
    "IsoWeekExpr",
    "IsoWeekYearExpr",
    "IsoDayOfWeekExpr",
    "DateFromPartsExpr",
    "DateToPartsExpr",
    "DateTruncExpr",
    # Window expressions
    "RankExpr",
    "DenseRankExpr",
    "DocumentNumberExpr",
    "ShiftExpr",
    "ExpMovingAvgExpr",
    "DerivativeExpr",
    "IntegralExpr",
    "CovariancePopExpr",
    "CovarianceSampExpr",
    "LinearFillExpr",
    "LocfExpr",
    "TopExpr",
    "BottomExpr",
    "TopNWindowExpr",
    "BottomNWindowExpr",
    # Encrypted string expressions
    "EncStrContainsExpr",
    "EncStrStartsWithExpr",
    "EncStrEndsWithExpr",
    "EncStrNormalizedEqExpr",
    # Query operators
    "QueryOperator",
    "And",
    "Or",
    "Not",
    "Nor",
    "Expr",
    "Eq",
    "Ne",
    "Gt",
    "Gte",
    "Lt",
    "Lte",
    "In",
    "Nin",
    "Regex",
    "Exists",
    "Type",
    "ElemMatch",
    "Size",
    "All",
    # Bitwise query operators
    "BitsAllClear",
    "BitsAllSet",
    "BitsAnyClear",
    "BitsAnySet",
    # Geospatial query operators
    "GeoIntersects",
    "GeoWithin",
    "Near",
    "NearSphere",
    # Misc query operators
    "Mod",
    "JsonSchema",
    "Where",
    "Text",
    # Accumulators
    "Accumulator",
    "Sum",
    "Avg",
    "Min",
    "Max",
    "First",
    "Last",
    "Push",
    "AddToSet",
    "StdDevPop",
    "StdDevSamp",
    "Count_",
    "MergeObjects",
    "Accumulate",
    "TopN",
    "BottomN",
    "FirstN",
    "LastN",
    "MaxN",
    "MinN",
    "merge_accumulators",
    # Stages
    "Match",
    "Project",
    "Group",
    "Sort",
    "Limit",
    "Skip",
    "Unwind",
    "Lookup",
    "AddFields",
    "Set",
    "Unset",
    "Count",
    "SortByCount",
    "Facet",
    "Bucket",
    "BucketAuto",
    "ReplaceRoot",
    "ReplaceWith",
    "Sample",
    "Out",
    "Merge",
    "Redact",
    "UnionWith",
    "GeoNear",
    "GraphLookup",
    "SetWindowFields",
    "Densify",
    "Fill",
    "Documents",
    # Statistics stages
    "CollStats",
    "IndexStats",
    "PlanCacheStats",
    # Session stages
    "ListSessions",
    "ListLocalSessions",
    "ListSampledQueries",
    # Change stream stages
    "ChangeStream",
    "ChangeStreamSplitLargeEvent",
    # Admin stages
    "CurrentOp",
    "ListClusterCatalog",
    "ListSearchIndexes",
    # Atlas search stages
    "Search",
    "SearchMeta",
    "VectorSearch",
    # Advanced stages
    "QuerySettings",
    "RankFusion",
]
